### PR TITLE
Fix deployment

### PR DESCRIPTION
**Pull request by Speykious**
Finally, we managed to publish this to Nuget!
This PR fixes CI deployment issues once and for all.

### CODE REVIEW

**Comment by Speykious** [comment]
Oof, I just realized that I didn't synchronize the CI workflow well. gimme a sec

**Comment by Speykious** [comment]
Well now it does, perfect :D

**Review by adryzz — APPROVED** [review]
LGTM, lets wait for ayane

**Review by sr229 — CHANGES_REQUESTED** [review]
If you're planning to actually fix this, then let's have a step for the Production environment, at the moment you're all deploying via the Pre-release environment. Create a dedicated deploy step for the Production environment.

**Comment by Speykious** [comment]
That's fine, however I don't think we need a *dedicated* deploy step for production. They'd both be the same without any modification. How about I just edit the environment as `environment: ${{ github.event.environment }}`?

**Comment by sr229** [comment]
> That's fine, however I don't think we need a _dedicated_ deploy step for production. They'd both be the same without any modification. How about I just edit the environment as `environment: ${{ github.event.environment }}`?

I tried that and it didn't work so the best course of action is hardocde it

**Review by sr229 — APPROVED** [review]

**Comment by Speykious** [comment]
Awesome! It looks like `${{ github.event.release.prerelease && 'Pre-release' || 'Production' }}` is a perfect fit.
The Production deployment "error" up there is just me cancelling it - we've already published the packages.

**Pull request merged**
